### ISSUE TITLE
Ability to hide icon from status bar

### ISSUE THREAD

**Issue by stepanp** [deseven/icanhazshortcut#13]
Please add an option to hide icon from status bar.

**Comment by deseven** [comment]
That's not a problem at all, but why?

**Comment by stepanp** [comment]
Because it just not needed there :) 
So, currently icon is unsightly and status bar looks more cleanly without extra icons

**Comment by deseven** [comment]
Ок, давай на русском.
Как тогда будем контролировать приложение? Через конфиги?
Или отдельным графическим конфигуратором?
В этом случае тогда наверное лучше делать общесистемный сервис в стиле mpd?

**Comment by deseven** [comment]
Или же просто показывать окно с настройками при повторном запуске?

**Comment by stepanp** [comment]
Да, давай.

> просто показывать окно с настройками при повторном запуске

Я за такой вариант

**Comment by deseven** [comment]
Хорошо, идея интересная, постараюсь сделать к следующему релизу.

**Comment by deseven** [comment]
[Latest release](https://deseven.info/sys/ichs.dmg)
