### ISSUE TITLE
Can't assign function keys

### ISSUE THREAD

**Issue by trodemaster** [deseven/icanhazshortcut#17]
Is there any way to have only a function key like F5 trigger the shortcut? Was not able to enter only a function key.

**Comment by deseven** [comment]
Looks like a bug, most likely in a hotkey selector.  
For now you can close iCHS and edit `$HOME/.config/iCanHazShortcut/config.ini` manually, simply enter they key you want and it will work.

**Comment by trodemaster** [comment]
Thanks will give it a try!

________________________________

**Comment by deseven** [comment]
fix released as [0.8.2](https://github.com/deseven/icanhazshortcut/releases/tag/0.8.2)

thanks for reporting!
