### ISSUE TITLE
Test run enhancements

### ISSUE THREAD

**Issue by deseven** [deseven/icanhazshortcut#2]

**Comment by ghost** [comment]
I think this should be added to the test run function, too.
The test run kills the command after 10 seconds but it can have undesirable results when performing local or remote operations (git push/pull, sendmail, cp, brew upgrade) when testing a command.
Some operations can stall and have no output for more than 10 seconds but still be active.

**Comment by deseven** [comment]
Current architecture is pretty simple and it doesn't monitor user commands - everything is executing in a "run-and-forget" manner.

Test run is different, though. Since we can't really understand whether the command hanged or just doing some work, i decided that it's not that common for a shortcut command to do something more than 10 seconds.

I guess the right solution here is to allow user to abort test run any time he want by pressing a button or something. I'll think about it later, 1.1 release is a priority now.

**Comment by ghost** [comment]
Just to add that if the test run window presented the command output in realtime (scrolling window like in the default terminal), then it would just need a **Cancel** button. Or, as an alternative, a button to run the test in the default terminal (to avoid complicating the code). Just an idea for a new issue.

**Comment by deseven** [comment]
I'll leave it all as one issue since it's easier to work on one particular part of functionality. Could be done for 1.2 or later.

**Comment by deseven** [comment]
No silly timeouts anymore, added the abort button (works [like that](https://d7.wtf/s/Screen%20Recording%202020-04-03%20at%2023.59.35.mp4)). Realtime output won't make it to the next version though, so I'll leave it open.

**Comment by deseven** [comment]
This is more complicated than i originally anticipated, going to postpone it again.

**Comment by deseven** [comment]
Since I have very little time to continue the development of this project, I decided to cancel some of the planned features, otherwise the new release will never be a thing. Test run will stay at it is, I think it's good enough anyway.
