### ISSUE TITLE
Mouse buttons

### ISSUE THREAD

**Issue by FossPrime** [deseven/icanhazshortcut#20]
Any chance we could assign mouse buttons?

**Comment by deseven** [comment]
Why? I honestly see no point in developing such a functionality...  
But! You can use [Karabiner](https://pqrs.org/osx/karabiner/) to assign any mouse button to any key (F13-F19 are perfect for that) and then just press that mouse button in iCHS hotkey selector.

**Comment by FossPrime** [comment]
I'll look into karabiner again. I need it to switch workspaces faster with
my extra side mouse (4 & 5) buttons.

**Comment by deseven** [comment]
Hmm... Even if i'll be able figure out how to grab mouse buttons i'm not sure how to test is reliably, my mouse only have 2 (well, actually 3) buttons. I'll see what i can do, but for now your best bet is to assign your mouse buttons to some keys via Karabiner.

**Comment by deseven** [comment]
Wait a sec, i found my old mouse and it has 2 additional buttons. So, what you need to do is:

1. Assign button4 to some free unused key, for example F20:
![](https://d7.wtf/TormentillaAnthramineAnapneic.png)

2. Make sure that your mouse is enabled in Devices tab:
![](https://d7.wtf/MetabolePyrodineCordiform.png)

3. Create a shortcut as usual, press your mouse button with active shortcut selector:
![](https://d7.wtf/GooseberryFadyDeprecative.png)

And that's it.

**Comment by FossPrime** [comment]
SOOOO glad Karabiner works on the Mac again... It's control and command swapping feature is better than the mac's built in.

**Comment by deseven** [comment]
Don't close it, i'll try to at least look into it in the future.

**Comment by deseven** [comment]
Actually there is no point to use iCHS for that at all. Karabiner is all you need, since those are system-level shortcuts anyway, you can simply redefine them in system shortcuts:
![](https://d7.wtf/GilbertInactivityGolkakra.png)
