### ISSUE TITLE
Action Name

### ISSUE THREAD

**Issue by ghost** [deseven/icanhazshortcut#24]
Please add a field to provide an action name, to have more meaningful titles showing up in the menubar, instead of the whole command gibberish.

**Comment by deseven** [comment]
Good idea.

**Comment by deseven** [comment]
@megadr01d looks like i'm finished with this and other tasks for 1.1 release.  
If you can test it, [please do](https://d7.wtf/s/ichs-dev.zip). Changes are pretty huge, so expect bugs (your config file will be backed up, though).

A couple of things worth mentioning about how i approached this task:  
1. "Action" was renamed to "Command", as action now acts as a name.
2. Action field is completely optional (for compatibility and common sense).
3. Menu entries will be populated from action if one exists (with a fallback to a full command).

**Comment by ghost** [comment]
Already downloaded and tested. Looks good, I like the "optional" approach to serve all user cases.
So far, no bugs detected, except some minor text alignment in the "About" window.
Thanks for the improvement. Closing this issue.

**Comment by deseven** [comment]
Cool, thanks.

> minor text alignment in the "About" window

Can you elaborate?

**Comment by ghost** [comment]
On the "created" and "icons by":

![image](https://user-images.githubusercontent.com/9649385/56093643-1ece9700-5ec3-11e9-8c18-cd65c41d9262.png)

**Comment by ghost** [comment]
OK, found 2 more bugs.

1. Open the **Shortcuts** window
2. Select a command (let's call it command1)
3. Edit it (pencil icon or double-click)
4. Cancel (apply changes works correctly and doesn't trigger the bug)
5. Select the same command (command1)
6. Add a new shortcut
7. Enter new shortcut key and command info
8. Apply changes

The original command (command1) gets overwritten.

The second bug is just a minor issue but, when editing a command, you need to press `Tab` / `Shift Tab` 2 times to switch between text fields.

**Comment by deseven** [comment]
fixed, fixed and fixed :)

**Comment by deseven** [comment]
I'm going to release 1.1 on friday if no one is going to find anything else.
