### ISSUE TITLE
Notifications with command output

### ISSUE THREAD

**Issue by ghost** [deseven/icanhazshortcut#25]
Add Notification Center notifications with the [action name](https://github.com/deseven/icanhazshortcut/issues/24) as the title and the action output as the subtitle.

**Comment by deseven** [comment]
I don't really want to do it because i don't want to read command outputs (which means i need to wait for program execution in another thread). You can just use [terminal-notifier](https://github.com/julienXX/terminal-notifier) to output what you want when you really need it.

**Comment by ghost** [comment]
You're right, I think `terminal-notifier` is the best flexible approach and can be easily enabled/disabled within the script. Thanks for the pointer.
