### ISSUE TITLE
Expand shell variables in workdir param

### ISSUE THREAD

**Issue by deseven** [deseven/icanhazshortcut#28]
2. Support shorthandles for the home dir. Currently only an absolute path is supported. `/Users/soulitude/dev` works but `~/dev` and `$HOME/dev` don't.

_Originally posted by @megadr01d in https://github.com/deseven/icanhazshortcut/issues/3#issuecomment-482984098_

**Comment by ghost** [comment]
Since the **Command** field [already expands shell variables](https://github.com/deseven/icanhazshortcut/issues/3#issuecomment-483454153), can't the **Workdir** do a simple `cd` before the `<path>`?

**Comment by deseven** [comment]
I thought about it but i'm not sure if it's a good idea to send something before user command. I need to test it first and maybe try to find some info about similar software or other people experience.

**Comment by deseven** [comment]
I think the only correct way to do that is to expand those variables when i register a shortcut using a shell defined in preferences.

It's pretty straightforward for typical variables, a simple `echo` will suffice. However, [tilde is a completely different story](https://stackoverflow.com/questions/3963716/how-to-manually-expand-a-special-variable-ex-tilde-in-bash) and i don't want to use any of the known solutions because to be honest each and every one of them is a mess. So i think i'm going to expand `~` manually by calling something like `cd ~ && pwd` or maybe just replacing it internally with `$HOME` or `/Users/$USER`.

**Comment by deseven** [comment]
@megadr01d it's done now. Tilda is always being expanded, because it's fast and secure. Variables, however, i decided to not touch at all, because it will complicate things a lot. But there is an option in "Preferences" tab now to always send a simple `cd` command just like you proposed above. This should do!

**Comment by ghost** [comment]
Great news, @deseven. Cheers!
