### ISSUE TITLE
Allow adding a command without a shortcut key

### ISSUE THREAD

**Issue by ghost** [deseven/icanhazshortcut#29]
Since this goes a bit against the scope of iCanHazShortcut, which is to assign system wide shortcuts to commands, I'm not sure about this one.

The reasoning for this is, when we get a long list of commands, we may eventually run out of available shortcut combinations. Since we can also see and execute commands from the menubar icon, maybe we could set commands that we don't run so often, without a shortcut, and execute them, manually from the menubar, when needed.

If a user prefers to hide the menubar icon, he just needs to make sure he assigned a shortcut to every command. It would be flexible for everyone.

Anyway, just a low priority suggestion. You can close this one if you feel it's not worth it.

**Comment by deseven** [comment]
To be honest i'm not sure if i like it or not, but this can be done easily so i may consider it in the future.
