### ISSUE TITLE
Workdir selection

### ISSUE THREAD

**Issue by deseven** [deseven/icanhazshortcut#3]

**Comment by ghost** [comment]
@deseven I just had the time to test the workdir option and found some things that could be improved:

1. In the **Shortcuts** window, add a **Workdir** column next to **Command**, so we can quickly see when a command is assigned a workdir.

2. Support shorthandles for the home dir. Currently only an absolute path is supported. `/Users/soulitude/dev` works but `~/dev` and `$HOME/dev` don't.

**Comment by deseven** [comment]
1. I don't think it's important to see a workdir in a shorctut list, what's the point in that?

2. That's a difficult one... Those variables are available only inside the shell you use and therefore can differ a lot. To expand them i either need to hardcode some stuff (like `~` or `$HOME` should expand to `/Users/username`) or to launch predefined shell before command execution to be able to know what those variables mean. Could be a good feature request as a new issue.

**Comment by ghost** [comment]
> I don't think it's important to see a workdir in a shorctut list, what's the point in that?

Say I have more than 1 entry with the same command (eg. `git sync`), no action name, but each has its own working dir. It would be easier to differentiate them.

> Could be a good feature request as a new issue.

OK. Maybe for later.

**Comment by deseven** [comment]
> Say I have more than 1 entry with the same command (eg. git sync), no action name, but each has its own working dir. It would be easier to differentiate them.

Oh, i think i have a better idea then! What if i add a possibility to select needed columns (and also to save that state, along with column sizes, etc)?

Like that:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/1761803/56098900-3f6c1080-5f06-11e9-957d-5c0c457264c6.png">

**Comment by ghost** [comment]
That would be simply beautiful.

**Comment by ghost** [comment]
Upon testing the workdir option further, I found that it works on the test run, as seen on the screencapture below. However, when invoking the command by shortcut or menubar, it doesn't run (nothing happens). Also tried a simple command like `open README.md` and the same thing occurs. Only works when doing a test run.

![image](https://user-images.githubusercontent.com/9649385/56170984-8a0b8c80-5fdb-11e9-9886-da0186ea159c.png)

Anyway, for the time being, I just remembered that I can simply do `cd ~/dev && git sync` without setting a workdir, which works correctly on the test run and by shortcut.

![image](https://user-images.githubusercontent.com/9649385/56171810-82011c00-5fde-11e9-8523-2c95f15ee4a0.png)

**Comment by deseven** [comment]
Yep, i totally forgot to reference workdir when running command via hotkey.  
[Dev build](https://d7.wtf/s/ichs-dev.zip) is updated in case you need it for your workflow right now.

**Comment by ghost** [comment]
So quick, man. Thanks, working great.
