### ISSUE TITLE
Customizable columns

### ISSUE THREAD

**Issue by deseven** [deseven/icanhazshortcut#30]
> Say I have more than 1 entry with the same command (eg. git sync), no action name, but each has its own working dir. It would be easier to differentiate them.

Oh, i think i have a better idea then! What if i add a possibility to select needed columns (and also to save that state, along with column sizes, etc)?

Like that:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/1761803/56098900-3f6c1080-5f06-11e9-957d-5c0c457264c6.png">

_Originally posted by @deseven in https://github.com/deseven/icanhazshortcut/issues/3#issuecomment-483056475_

**Comment by ghost** [comment]
Also make the window resizable (or a little wider, at least), if possible.

**Comment by deseven** [comment]
Resizable interface is a completely different story, please create another issue if you need it.
