### ISSUE TITLE
Option to manually check for updates

### ISSUE THREAD

**Issue by ghost** [deseven/icanhazshortcut#31]
I have **Check for updates** enabled in Preferences, but I got no notification of the new 1.1.0 version, even after rebooting. Is this function working and, if so, when exactly does ICHS check for updates?

**Comment by deseven** [comment]
Current policy for release versions is to wait 24 hours after launch so user won't become annoyed with an update prompt. For example, if you started your computer to do some work and have no intention to update anything or if you are a new user who installed ichs from a possibly outdated source (like brew cask).

This was (is) a temporary solution before moving to in-place upgrade system where user just has to press a button to update.

There is also no way to enforce this check any time you want, i should probably add that to the menu.

**Comment by deseven** [comment]
Oh i forgot about frequency, it's also 24 hours.  

So it goes like this:  
1st check - 24 hours after launch  
2nd check - 48 hours  
3rd check - 72 hours  
etc

**Comment by ghost** [comment]
Great, thanks.

I actually don't mind even getting update notifications on a weekly or monthly basis, I was just wondering, in case there could be a bug somewhere.

Anyway, a menu option or a button in the **About** screen to manually check for updates, would be nice. I'll change the title and make this a low priority feature request.
