### ISSUE TITLE
Notification Banner

### ISSUE THREAD

**Issue by Aristomastrosi** [deseven/icanhazshortcut#33]
Love this little tool. It would be perfect if after a shortcut has been activited we could configure to automatically display a notification banner with the given shortcut name. There is a workaround to use an additional osascript command like:

osascript -e 'display notification "" with title "Internal Speakers" subtitle "Sound Output"'

But if it would come out of the box, that would be brilliant.

**Comment by deseven** [comment]
Hey.

This was requested before in #25 and unfortunately at this point i have nothing to add. I may return to this later, though.

Thanks for your feedback in any case.
