### ISSUE TITLE
iCHS not working under MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by 111andre111** [deseven/icanhazshortcut#34]
At the moment iCHS is not working for me under Catalina in the sense that the Keyboard shortcuts don't work. How can I change that?
Is there maybe somewhere any logfile I can refer to, that tells me what is happening, when I press one of the iCHS keyboard shortcuts?

**Comment by deseven** [comment]
Hm... I'm on 10.15.2 and it works totally fine. I'm afraid that there is no logging right now.

Just in case - are you using the latest version (1.1.0)?  
Is that the case for all possible shortcuts? Try creating something simple, like `say hello` binded on F5.

**Comment by 111andre111** [comment]
Oh, sorry, that helped.
I don't know why, but I didn't realize, that the path to terminal location changed that I have in my explicit command.
Before it was
`       /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal`
and now is
`/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal`

So issue can be closed now as this is working now again. Sorry for not testing that `say` thing. Thank you for the hint.
