### ISSUE TITLE
Resizable Window

### ISSUE THREAD

**Issue by dmland** [deseven/icanhazshortcut#35]
Would like to be able to resize the window from the lower-right corner.

**Comment by deseven** [comment]
@dmland you can help with testing if you want, development version can be downloaded [here](https://d7.wtf/s/ichs-dev.zip).

What it does:
1. Window is resizable now (with lower limit of 600x300 and upper of 1280x720).
2. All controls in all cases should follow window's size.
3. Window's size and position are saved in config and restored upon every start.
