### ISSUE TITLE
Import/Export shortcuts via AppleScript

### ISSUE THREAD

**Issue by dmland** [deseven/icanhazshortcut#36]
It's nice to be able to view the defined shortcuts via AppleScript (and to toggle them), but it would be nice to be able to export them (TSV would be fine) and import them, which would permit backup and sharing shortcut sets.

**Comment by deseven** [comment]
TSV is not that great of a format to use for exporting/importing stuff. I should think about proper solution for this (JSON?).

Right now, for backup purposes, you can just grab the ichs config from `~/.config/iCanHazShortcut/config.ini`. It's very easy and human readable.

**Comment by dmland** [comment]
The config file is sufficient. Thank you. No further action required.
