### ISSUE TITLE
Shortcuts not written to disk

### ISSUE THREAD

**Issue by markkrieg** [deseven/icanhazshortcut#37]
I just discovered this app and it is a gem! However, it does not record to disk the Shortcuts that I add to it. After a reboot they're gone.

MacOS 10.15.4
MacBook Pro (16-inch, 2019)

**Comment by deseven** [comment]
Can you please check if your config file actually exists? It should be located in `~/.config/iCanHazShortcut`.

**Comment by deseven** [comment]
Closing for the lack of feedback.
