### ISSUE TITLE
Unable to Map Clear/Numlock Button

### ISSUE THREAD

**Issue by schuyberg** [deseven/icanhazshortcut#38]
I'm hoping to use icanhazshortcut to enable the 'numlock' button on my CoolerMaster Pro M keyboard with a script, but unfortunately I can't map the the 'numock' button on my keyboard because it functions as 'clear' as well and clears the currently selected shortcut instead of creating a mapping. Is there any way around this?

**Comment by deseven** [comment]
I've added the support for Clear button, both as a single key and as a hotkey with modifiers. Unfortunately I'm too deep into 1.2 release to make a small update right now, but you can download dev version with this fix [here](https://d7.wtf/s/ichs-dev.zip).

**Comment by schuyberg** [comment]
perfect - thank you!
