### ISSUE TITLE
[stderr] automator Cache location entry for Photos.app

### ISSUE THREAD

**Issue by johannhuang** [deseven/icanhazshortcut#40]
```sh
automator '.../New Microsoft Edge Window.workflow'
```

```applescript
on run {input, parameters}
	
	tell application "Microsoft Edge"
    	make new window
    	activate
	end tell
	
	return input
end run
```

```
[stderr]
2020-07-15 19:02:46.841 automator[95181:26514832] Cache location entry for /System/Applications/Photos.app in cache file at /Users/.../Library/Caches/com.apple.automator.actionCache-bundleLocations.plist is not valid: Location /System/Applications/Photos.app has been modified.
```

As you can see, I don't use Photos.app related actions, and I am wondering what is the problem. Hope anyone can help.

**Comment by deseven** [comment]
On the first run macOS asked you for a permission to control another process. If you somehow missed it you can enable it here:
![](https://d7.wtf/s/PigmentophageJoanneFondling.png)

Ignore the error about photos app, it does that in Terminal too, probably some bug.

P.S. If you use automator only for applescript, it might be better to just put applescript in a text file and call it like that - `osascript .../New Microsoft Edge Window.applescript`

**Comment by johannhuang** [comment]
@deseven Thanks for your response. 

Yeah, I also have just found out today that automator is not necessary after I got myself familiar with the automation on macOS. My main usage of iCanHazShortcut is for assigning global keyboard shortcut to actions/applications/workflows. 

iCanHazShortcut is better than Automator in the sense that it doesn't always trigger notification that I need to assign accessibility from A to B, such as from Safari to Chrome if I call the General Service in Chrome to trigger actions in Safari. 

I adopted automator since my first try was with Automator and then I shifted to iCanHazShortcut. Thanks for your suggestion, now I can just get rid of Automator by just utilizing `osascipt` and even no applescript any more but just JavaScript (also one of my new gain today).

**Comment by deseven** [comment]
I see. Just in case you'll need to create a notification you can use standard `display notification` from applescript or [terminal-notifier](https://github.com/julienXX/terminal-notifier) (may give you more flexibility).

Did the permission thing help? Can i close this issue (or you can close it yourself)?

**Comment by johannhuang** [comment]
Thanks again. In fact, I allowed the permission at my first try. For the Photos.app-relating error, I guess it is still a hidden problem of possibly Automator itself. I think there is nothing more to do with iCanHazShortcut, so I close this issue.
