### ISSUE TITLE
ICanHazShortcut leaves a zombie bash every time it's used

### ISSUE THREAD

**Issue by ghost** [deseven/icanhazshortcut#41]
![](https://jzgm.qonq.gq/)

**Comment by deseven** [comment]
I correctly detach from the launched process after sending the needed data and EOF. It's an upstream bug, unfortunately. I reported it, but it's hard to tell when it will be fixed.

I'll try to go around it somehow. The behavior is really strange, not every run creates a zombie process, only some.

Thanks for reporting!

**Comment by deseven** [comment]
I managed to fix it by rewriting the invocation using native NSTask. All actions triggered by hotkeys or menu events should not leave zombies anymore (test run still uses the old system, but i'll deal with it later).

@ledlamp no pressure, obviously, but you would help immensely by testing the fix which is already available in [the dev build](https://d7.wtf/s/ichs-dev.zip) :)

**Comment by ghost** [comment]
I installed that dev build and it doesn't appear to be leaving zombie bashes. I'll check again after a while of normal use. Also nice domain lol

**Comment by ghost** [comment]
Yep, no zombies. Process list looks peaceful.

**Comment by deseven** [comment]
Cool, i'm going to close it then. The fix will go to version 1.3, but you can continue using the dev build, it will find the update when it will be released. Thanks for testing!
