### ISSUE TITLE
after restart all shortcuts are gone, serveral times

### ISSUE THREAD

**Issue by ak-kc** [deseven/icanhazshortcut#51]
Can u please help with this problem?

**Comment by deseven** [comment]
1. Is your `~/.config` directory writable?
2. Is there a `~/.config/iCanHazShortcut/config.ini` file? If yes, what does it contain?
3. What version of macOS are you using?

**Comment by ak-kc** [comment]
Hey, thank you for the answer. There is not even a .config folder, which i could open using "go to" with path "~/.config" in the finder. Its MacOS 10.15.7
 BTW: The problem also appears if i just turn ICHS off and on again.

best

**Comment by deseven** [comment]
Interesting. Well, what if you create a `.config` directory in your home folder manually?

**Comment by ak-kc** [comment]
Finder tells me, that this is not allowed. Because the folder starts with ".".

**Comment by deseven** [comment]
Can you create any dirs in your home directory at all?

**Comment by ak-kc** [comment]
yes

**Comment by ak-kc** [comment]
There was a problem with the permissions of the .config folder. I restored them and now it just works fine. Thank you for the hint. https://apple.stackexchange.com/questions/320682/ownership-of-the-config-folder-in-home-directory

**Comment by deseven** [comment]
Glad you sorted this out!
I also made a small change to output filesystem errors instead of just failing silently.
