### ISSUE TITLE
Memory YIKES

### ISSUE THREAD

**Issue by tgwaste** [deseven/icanhazshortcut#54]
![Screen Shot 2022-09-23 at 2 43 05 PM](https://user-images.githubusercontent.com/690918/192060747-184a4413-bea0-4c8b-8b14-4380f3e02725.png)

I mean really?? :)

**Comment by deseven** [comment]
@tgwaste whoa, what version of iCHS is that and on what macOS? It should only use around 30-40MB.

**Comment by deseven** [comment]
Anyone can confirm it with a way to reproduce it?
